const { cmd } = require('../command');

cmd({
    pattern: 'github',
    desc: 'Fetch GitHub user profile information.',
    category: 'search',
    react: '🐙',
    filename: __filename
}, async (conn, mek, m, { from, args, q, reply }) => {
    try {
        if (!q) return await reply("Hey! Please provide a GitHub username so I can look it up for you. 😊");

        
        const response = await fetch(`https://api.github.com/users/${q}`);
        
        if (!response.ok) {
            return await reply("Aww, I couldn't find that user. Are you sure the username is correct? 🔍");
        }

        const data = await response.json();
        
        
        let userInfo = `*✨ BLK QUEEN V1 GITHUB SEARCH ✨*

*👤 Name:* ${data.name || 'Not provided'}
*🔗 Username:* ${data.login}
*📝 Bio:* ${data.bio || 'No bio available'}

*📁 Public Repos:* ${data.public_repos}
*👥 Followers:* ${data.followers}
*🤝 Following:* ${data.following}
*📍 Location:* ${data.location || 'Unknown'}
*📅 Joined:* ${new Date(data.created_at).toLocaleDateString()}

*🔗 Profile:* ${data.html_url}

_Generated by BLACK QUEEN MD V1_ 🚀`;

        await conn.sendMessage(from, { 
            image: { url: data.avatar_url }, 
            caption: userInfo 
        }, { quoted: mek });

    } catch (e) {
        console.log(e);
        await reply("Oops! Something went wrong while fetching the data. Please try again later! 🌸");
    }
});
